name: Upload Latest Release to Azure Blob Storage

on:
  workflow_dispatch: # This triggers the workflow manually
  release:
    types: [published]

jobs:
  upload-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az storage -h

    - name: Get latest release asset URL
      id: get_asset
      run: |
        asset_url=$(curl -s "https://api.github.com/repos/freespoke/${GITHUB_REPOSITORY}/releases/latest" | jq -r '.zipball_url')
        echo "::set-output name=url::$asset_url"

    - name: Upload release to Azure Blob Storage
      run: |
        az storage blob upload \
          --account-name ffmobilesource \
          --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
          --container-name downloads \
          --file $(basename ${{ steps.get_asset.outputs.url }}) \
          --name freespoke-mobile-ios.zip
